#!/usr/bin/env python3
"""Audit GNU Radio Companion XML flowgraphs."""

from __future__ import annotations

import argparse
import hashlib
import sys
import xml.etree.ElementTree as ET
from collections import Counter, defaultdict
from pathlib import Path


HARDWARE_BLOCK_MARKERS = (
    "osmosdr_",
    "uhd_usrp_",
    "rtlsdr",
    "fcd",
    "audio_",
)

TRANSMIT_MARKERS = (
    "usrp_sink",
    "osmosdr_sink",
    "hackrf_sink",
)

PATH_KEYS = {"file", "filename", "path"}


def block_params(block: ET.Element) -> dict[str, str]:
    params: dict[str, str] = {}
    for param in block.findall("param"):
        key = (param.findtext("key") or "").strip()
        value = (param.findtext("value") or "").strip()
        if key:
            params[key] = value
    return params


def parse_flow(path: Path) -> dict[str, object]:
    data = path.read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    root = ET.fromstring(data)
    blocks = root.findall("block")
    connections = root.findall("connection")
    block_keys = [(block.findtext("key") or "").strip() for block in blocks]
    ids = []
    file_paths = []
    hardware = []
    tx_like = []
    outdated = []
    disabled = []

    for block in blocks:
        key = (block.findtext("key") or "").strip()
        params = block_params(block)
        block_id = params.get("id", "")
        if block_id:
            ids.append(block_id)
        enabled = params.get("enabled", "True")
        if enabled == "False":
            disabled.append(block_id or key)
        if key.startswith("gr_") or key.startswith("blks2_"):
            outdated.append(key)
        if any(marker in key for marker in HARDWARE_BLOCK_MARKERS):
            hardware.append(f"{block_id or key} ({key})")
        if any(marker in key for marker in TRANSMIT_MARKERS):
            tx_like.append(f"{block_id or key} ({key})")
        for param_key, value in params.items():
            if param_key in PATH_KEYS or value.startswith(("/", "~")):
                file_paths.append(f"{block_id or key}.{param_key}={value}")

    duplicate_ids = sorted(name for name, count in Counter(ids).items() if count > 1)
    return {
        "path": path,
        "sha256": digest,
        "blocks": len(blocks),
        "connections": len(connections),
        "block_keys": block_keys,
        "outdated": sorted(set(outdated)),
        "hardware": hardware,
        "tx_like": tx_like,
        "file_paths": file_paths,
        "disabled": disabled,
        "duplicate_ids": duplicate_ids,
    }


def render_report(results: list[dict[str, object]]) -> str:
    by_hash: dict[str, list[str]] = defaultdict(list)
    for result in results:
        by_hash[str(result["sha256"])].append(Path(result["path"]).name)

    lines = [
        "# GNU Radio Flow Audit",
        "",
        "Generated by `tools/audit_flows.py`. Flowgraph XML is treated as data only.",
        "",
        "## Summary",
        "",
        f"- Files audited: {len(results)}",
        f"- XML parse failures: 0",
        f"- Exact duplicate payload groups: {sum(1 for names in by_hash.values() if len(names) > 1)}",
        "",
        "## Findings",
        "",
    ]

    for result in sorted(results, key=lambda item: Path(item["path"]).name.lower()):
        path = Path(result["path"])
        lines.extend(
            [
                f"### {path.name}",
                "",
                f"- Blocks: {result['blocks']}",
                f"- Connections: {result['connections']}",
                f"- SHA-256: `{result['sha256']}`",
            ]
        )
        for label, key in (
            ("Outdated block keys", "outdated"),
            ("Hardware/audio endpoints", "hardware"),
            ("Transmitter-like non-file sinks", "tx_like"),
            ("Absolute or explicit file paths", "file_paths"),
            ("Disabled blocks", "disabled"),
            ("Duplicate block IDs", "duplicate_ids"),
        ):
            values = result[key]
            if values:
                lines.append(f"- {label}:")
                lines.extend(f"  - `{value}`" for value in values)
        lines.append("")

    duplicate_groups = [names for names in by_hash.values() if len(names) > 1]
    if duplicate_groups:
        lines.extend(["## Exact Duplicates", ""])
        for names in duplicate_groups:
            lines.append("- " + ", ".join(f"`{name}`" for name in sorted(names)))
        lines.append("")

    return "\n".join(lines)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("flow_dir", type=Path)
    parser.add_argument("--report", type=Path)
    args = parser.parse_args(argv)

    paths = sorted(
        path
        for path in args.flow_dir.iterdir()
        if path.is_file() and (".grc" in path.name or path.name.endswith(".fuzz"))
    )
    results = []
    failures = []
    for path in paths:
        try:
            results.append(parse_flow(path))
        except ET.ParseError as exc:
            failures.append(f"{path}: XML parse error: {exc}")

    if failures:
        for failure in failures:
            print(failure, file=sys.stderr)
        return 1

    report = render_report(results)
    if args.report:
        args.report.write_text(report + "\n", encoding="utf-8")
    else:
        print(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
